import express from 'express';
import PDFDocument from "pdfkit";
import fs from "fs";

const app = express();

app.get('/', function (req, res, next) {
    res.setHeader('Content-Type', 'text/html');
    res.write("<html> <body>");
    res.write('<p>index (welcome page) of essai_pdfkit</p>');
    res.write('<a href="generate-pdf">generate-pdf</a><br/>');
    res.write("</body></html>");
    res.end();
});

// Route to generate PDF
app.get("/generate-pdf", (req, res) => {
  // Create a new PDF document
  const doc = new PDFDocument();

  // Set response headers
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", "attachment; filename=example.pdf");

  // Pipe PDF data directly to response
  doc.pipe(res);

  // Add title and styling
  doc.fontSize(20).text("Dynamic PDF Generation in Node.js", { align: "center" });
  doc.moveDown();

  // Add custom content
  doc.fontSize(12).text("This PDF is dynamically generated using the pdfkit library in Node.js.");
  doc.moveDown();

  // Add some dynamic data
  const user = {
    name: "Didier Defrance",
    email: "didier@d-defrance.fr",
    amount: "250",
  };

  doc.text(`Customer Name: ${user.name}`);
  doc.text(`Email: ${user.email}`);
  doc.text(`Amount Due: ${user.amount}`);
  doc.moveDown();

  // Add an image (optional)
  try {
    doc.image("logo.png", { fit: [100, 100], align: "center" });
  } catch (e) {
    doc.text("Logo not found, skipping image section.");
  }

  // Add footer
  doc.moveDown();
  doc.fontSize(10).text("Generated by Node.js using PDFKit", { align: "center" });

  // Finalize the PDF
  doc.end();
});

// Start server
app.listen(3000, () => console.log("Server running on http://localhost:3000"));